documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: "*.md"
enhancement:
  - any:
      - changed-files:
          - any-glob-to-any-file: ".github/**/*"
          - any-glob-to-any-file: ".pre-commit-config.yaml"
